<a href="https://colab.research.google.com/github/19PA1A04A4/10-03-2020/blob/master/Assignement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [0]:
sp=pd.read_csv("students_placement_data.csv")#reading the file

In [0]:
sp.describe()

Roll No  SSC Percentage  ...  B.Tech_percentage    Backlogs
count  117.000000      117.000000  ...         117.000000  117.000000
mean    59.000000       80.324359  ...          62.943419    4.111111
std     33.919021        8.879266  ...          12.064306    6.335148
min      1.000000       47.800000  ...          31.200000    0.000000
25%     30.000000       76.000000  ...          54.180000    0.000000
50%     59.000000       82.330000  ...          64.360000    0.000000
75%     88.000000       87.000000  ...          72.570000    7.000000
max    117.000000       93.660000  ...          88.100000   25.000000

[8 rows x 5 columns]

In [0]:
sp.isna().any()#finding na values

Roll No                               False
Gender                                False
Section                               False
SSC Percentage                        False
inter_Diploma_percentage              False
B.Tech_percentage                     False
Backlogs                              False
registered_for_ Placement_Training    False
placement status                      False
dtype: bool

In [0]:
x=sp[['SSC Percentage','inter_Diploma_percentage']]
y=sp['B.Tech_percentage']

In [0]:
x.shape

(117, 2)

In [0]:
y.shape

(117,)

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12) #splitting the data into two parts

In [0]:
model=LinearRegression()
model.fit(X_train,y_train)#fitiing linear regression

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model.intercept_

-7.12367136639908

In [0]:
model.coef_

array([0.1354934, 0.7301277])

In [0]:
sp1=sp.loc[sp['Gender']=='M'] #seperating male students

In [0]:
x=sp1['inter_Diploma_percentage'].values.reshape(-1,1)
y=sp1['B.Tech_percentage'].values.reshape(-1,1)

In [0]:
x.shape

(68, 1)

In [0]:
y.shape

(68, 1)

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=123)

In [0]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model.intercept_

array([-1.61277228])

In [0]:
model.coef_

array([[0.75849346]])

In [0]:
pred=model.predict([[72]])#predicting b.tech percentage from inter percentage of 72% for male students 
pred

array([[52.99875697]])

In [0]:
sp2=sp.loc[sp['Gender']=='F']#seperating Female studests

In [0]:
sp2.describe()

Roll No  SSC Percentage  ...  B.Tech_percentage   Backlogs
count   49.000000       49.000000  ...          49.000000  49.000000
mean    58.142857       82.911633  ...          71.199388   0.714286
std     31.077189        8.040363  ...           7.686968   2.140872
min      2.000000       50.660000  ...          45.260000   0.000000
25%     33.000000       80.300000  ...          65.700000   0.000000
50%     61.000000       84.840000  ...          72.400000   0.000000
75%     85.000000       87.420000  ...          75.960000   0.000000
max    105.000000       93.660000  ...          88.100000  13.000000

[8 rows x 5 columns]

In [0]:
x=sp2['inter_Diploma_percentage'].values.reshape(-1,1)
y=sp2['B.Tech_percentage'].values.reshape(-1,1)

In [0]:
x.shape

(49, 1)

In [0]:
y.shape

(49, 1)

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=213)

In [0]:
model.intercept_

array([-1.61277228])

In [0]:
model.coef_             

array([[0.75849346]])

In [0]:
model.predict([[72]])#predicting b.tech percentage for inter percentage of 72% of female students

array([[52.99875697]])

Therefore female students are performing better in b.tech than male students with inter percentage of 72%